In [1]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.11/dist-packages (1.1.3)

In [21]:
import duckdb

conn = duckdb.connect("my_database.db")
print("✅ Connected to DuckDB file my_database.db!")

✅ Connected to DuckDB file my_database.db!

In [23]:
# Load a CSV file into DuckDB
#https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv
conn.execute("""
    CREATE OR REPLACE TABLE sales_data AS
    SELECT * FROM read_csv_auto('/content/OLAP_Data.csv')
""")

print("✅ CSV Data Loaded into DuckDB!")

✅ CSV Data Loaded into DuckDB!

In [25]:
# Query to preview the first 5 rows of the sales_data table
preview_query = "SELECT * FROM sales_data LIMIT 5"

df_preview = conn.execute(preview_query).fetchdf()
display(df_preview)

   Year Quarter    Month Product   Region  Sales_Amount
0  2022      Q1  Month-1  Laptop      USA         16795
1  2022      Q1  Month-1  Laptop       UK          1860
2  2022      Q1  Month-1  Laptop  Germany         39158
3  2022      Q1  Month-1  Laptop   France         45732
4  2022      Q1  Month-1  Laptop    Japan         12284

In [26]:
#Query using SQL
query = """
SELECT
    Year, Product, Region, SUM(Sales_Amount) AS Total_Sales
FROM sales_data
WHERE Region IN ('USA', 'UK') AND Year >= 2023
GROUP by Year, Region, Product
ORDER BY Total_Sales DESC
"""

df_result = conn.execute(query).fetchdf()
df_result

    Year     Product Region  Total_Sales
0   2023      Tablet    USA    1476870.0
1   2023      Tablet     UK    1346931.0
2   2024  Smartwatch    USA    1340947.0
3   2023      Laptop     UK    1325803.0
4   2023      Laptop    USA    1302526.0
5   2024  Smartwatch     UK    1296840.0
6   2023  Smartwatch    USA    1284780.0
7   2024  Headphones     UK    1283754.0
8   2023  Smartphone    USA    1275323.0
9   2023  Headphones     UK    1259898.0
10  2024  Headphones    USA    1247202.0
11  2023  Smartphone     UK    1240616.0
12  2024      Tablet    USA    1237432.0
13  2024      Tablet     UK    1186456.0
14  2023  Headphones    USA    1181710.0
15  2024      Laptop     UK    1181585.0
16  2024      Laptop    USA    1172985.0
17  2024  Smartphone     UK    1159595.0
18  2024  Smartphone    USA    1154148.0
19  2023  Smartwatch     UK    1126355.0

In [27]:
conn.close()
print("✅ DuckDB connection closed!")

✅ DuckDB connection closed!