In [25]:
import numpy as np
import pandas as pd
import random

In [11]:
#df = pd.DataFrame([[100,20],[200,25],[300,35],[400,10]], columns=['Vent','Freq'])

In [38]:
rng = np.random.RandomState(2021)

In [68]:
ST_Percent_Return = rng.normal(2,0.3,100)
MT_Percent_Return = rng.normal(5,2.5,100)
LT_Percent_Return = rng.normal(6.25,5.5,100)

In [40]:
Invest = 300000
Port = [Invest*.45, Invest*.35, Invest*.20]

In [41]:
Port

[135000.0, 105000.0, 60000.0]

In [70]:
df=[]

In [71]:
df = pd.DataFrame(list(zip(ST_Percent_Return, MT_Percent_Return, LT_Percent_Return)), columns=['ST_%return', 'MT_%return', 'LT_%return'])

In [72]:
df['ST_Return'] = ST_Percent_Return*Port[0]/100

In [ ]:
df

In [73]:
df['MT_Return'] = MT_Percent_Return*Port[1]/100
df['LT_Return'] = LT_Percent_Return*Port[2]/100

In [74]:
df

    ST_%return  MT_%return  LT_%return    ST_Return    MT_Return    LT_Return
0     1.364769    7.439400    9.756977  1842.438374  7811.370147  5854.185912
1     1.689956    2.804288    3.470147  2281.440248  2944.502453  2082.088150
2     2.372979    7.466301    3.173667  3203.521131  7839.616144  1904.199939
3     1.844783    4.153520    7.428609  2490.457535  4361.195637  4457.165406
4     2.186765    5.105307    3.890664  2952.132829  5360.572354  2334.398184
..         ...         ...         ...          ...          ...          ...
95    1.639039    7.750302    3.223527  2212.702635  8137.816679  1934.116041
96    1.796567    4.312129    2.844120  2425.364898  4527.735674  1706.472291
97    1.871764    3.413797    2.724779  2526.881693  3584.487077  1634.867375
98    2.024977    0.422828    8.460409  2733.718644   443.969054  5076.245346
99    1.649026    1.886385    7.420071  2226.184591  1980.704390  4452.042518

[100 rows x 6 columns]

In [78]:
df['Total Return']=(df.ST_Return+df.MT_Return+df.LT_Return)

In [ ]:
df

In [80]:
df['Ending Balance']=df['Total Return']+Invest

In [81]:
df

,ST_%return,MT_%return,LT_%return,ST_Return,MT_Return,LT_Return,Total Return,Ending Balance
0,1.364769,7.439400,9.756977,1842.438374,7811.370147,5854.185912,15507.994433,315507.994433
1,1.689956,2.804288,3.470147,2281.440248,2944.502453,2082.088150,7308.030852,307308.030852
2,2.372979,7.466301,3.173667,3203.521131,7839.616144,1904.199939,12947.337214,312947.337214
3,1.844783,4.153520,7.428609,2490.457535,4361.195637,4457.165406,11308.818578,311308.818578
4,2.186765,5.105307,3.890664,2952.132829,5360.572354,2334.398184,10647.103367,310647.103367
...,...,...,...,...,...,...,...,...
95,1.639039,7.750302,3.223527,2212.702635,8137.816679,1934.116041,12284.635354,312284.635354
96,1.796567,4.312129,2.844120,2425.364898,4527.735674,1706.472291,8659.572864,308659.572864
97,1.871764,3.413797,2.724779,2526.881693,3584.487077,1634.867375,7746.236144,307746.236144
98,2.024977,0.422828,8.460409,2733.718644,443.969054,5076.245346,8253.933043,308253.933043
99,1.649026,1.886385,7.420071,2226.184591,1980.704390,4452.042518,8658.931499,308658.931499

In [87]:
Balance_mean = np.mean(df['Ending Balance'])
Balance_stdev = np.std(df['Ending Balance'])

In [88]:
print(Balance_mean, Balance_stdev)

311415.6193357559 4243.780877833321